playerandenemies:
	cl /Fe:playerandenemies.exe -Ic:\packages\pdcurses\PDCurses-3.9 main.cpp c:\packages\pdcurses\PDCurses-3.9\wincon\pdcurses.lib c:\packages\pdcurses\PDCurses-3.9\wincon\pdckbd.obj c:\packages\pdcurses\PDCurses-3.9\wincon\pdcscrn.obj c:\packages\pdcurses\PDCurses-3.9\wincon\pdcutil.obj c:\packages\pdcurses\PDCurses-3.9\wincon\pdcclip.obj "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22000.0\um\x64\User32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22000.0\um\x64\Advapi32.lib"


clean:
	del playerandenemies.exe
	del main.obj
